name: esc_pos_utils
description: Basic Flutter/Dart classes for ESC/POS printing. Ticket class generates ESC/POS commands that can be sent to a thermal printer.
version: 0.3.6
homepage: https://github.com/andrey-ushakov/esc_pos_utils

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hex:
  gbk_codec:
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
